*HEADING
************************************************************************
Project name:
tyre size:
OE:
user:
date:
************************************************************************
*parameter
****load details---------------------
load1_kg=
load2_kg=
load3_kg=
pressure1=
speed_kmph=
IA=
SA=
SR=
****RIM_details---------------------
width=
diameter=
**********-----------------------
inflation_pressure1=0.00689476*pressure1
inflation_pressure2=0.00689476*pressure2
inflation_pressure3=0.00689476*pressure3
load1=9.81*load1_kg
load2=9.81*load2_kg
load3=9.81*load3_kg
speed=speed_kmph*1000*1000/3600
****RIM_Movement---------------------
rimdisp_plus = 60.0
rimdisp_minus = -60.0